# Generated by Django 5.0.4 on 2024-04-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmtype', models.CharField(max_length=50)),
                ('nobeds', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('uname', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
                ('status', models.CharField(default='NS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('idproof', models.ImageField(upload_to='images/')),
                ('photo', models.ImageField(upload_to='images/')),
                ('uname', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
                ('status', models.CharField(default='User', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='images/')),
                ('vname', models.CharField(max_length=50)),
                ('vnumber', models.CharField(max_length=50)),
                ('vphoto', models.ImageField(upload_to='images/')),
                ('mincharge', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('uname', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
                ('status', models.CharField(default='NT', max_length=50)),
            ],
        ),
    ]
