# Generated by Django 5.0.4 on 2024-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('bdate', models.DateField()),
                ('custid', models.IntegerField()),
                ('custname', models.CharField(max_length=50)),
                ('rtype', models.CharField(max_length=50)),
                ('datef', models.DateField()),
                ('dateto', models.DateField()),
                ('nod', models.IntegerField()),
                ('totamt', models.IntegerField()),
                ('cardno', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='bsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('bdate', models.DateField()),
                ('rtype', models.CharField(max_length=50)),
                ('rno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='temp1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField()),
            ],
        ),
    ]
