# Generated by Django 5.0.4 on 2024-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_bsub_temp_temp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nop',
            field=models.IntegerField(default=0),
        ),
    ]
