from django.urls import path
from . import views
urlpatterns = [
    path('',views.index),
    path('h/',views.index),
    path('urg/',views.userregistration),
    path('srg/',views.staffregistration),
    path('trg/',views.taxiregistration),
    path('login/',views.login),
    path('svp/', views.showvehicleownerpage),
    path('ssp/',views.showstaffpage),
    path('sup/',views.showuserpage),
    path('sap/',views.showadminpage),
    path('sapp/',views.staffapproval),
    path('sappr/<int:id>/',views.staffapprove),
    path('sarej/<int:id>/',views.staffreject),
    path('tapp/',views.taxiapproval),
    path('tappr/<int:id>/',views.taxiapprove),
    path('tarej/<int:id>/',views.taxirejct),
    path('addroom/',views.addroom),
    path('rtype/',views.addroomtype),
    path('vroom/',views.viewrooms),
    path('eddr/<int:id>/',views.editroomtype),
    path('der/<int:id>/',views.deleteroom),
    path('veiwroom/',views.listrooms),
    path('edroom/<int:id>/',views.edroom),
    path('rtable/',views.roomtables),
    path('bookrm/<int:id>/',views.bookingform),
    path('pick/<int:rno>/',views.pickroom),
    path('del/<int:rno>/',views.deleteroom),
    path('pay/',views.pay),
    path('mybk/',views.mybookings),
    path('vmore/<int:bno>/',views.viewmore),
    path('delroom/<int:bno>/',views.delroom),
    path('allrooms/',views.allrooms),
    path('rbkings/',views.roombookings),
]